apiVersion: apps/v1

kind: Deployment

metadata:
  name: lobo-codes

spec:
  replicas: 3
  selector:
    matchLabels:
      app: lobo-codes
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: lobo-codes
    spec:
      containers:
        - name: lobo-codes
          image: localhost:32000/lobo-codes:latest
          imagePullPolicy: Always
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: OTLP_SERVER
              value: "$(JAEGER_CASSANDRA_COLLECTOR_SERVICE_HOST)"
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https

