apiVersion: apps/v1

kind: Deployment

metadata:
  name: cassandra-client

spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra-client
  template:
    metadata:
      labels:
        app: cassandra-client
    spec:
      containers:
        - name: go-app-container
          image: localhost:32000/golang-cassandra-client:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080

